#ifndef __ANN_FILE_HEADER_H__
#define __ANN_FILE_HEADER_H__

enum ANN_FILE_HEADER_LIST
{
	ANN_HEADER_APPLICATION,
	ANN_HEADER_TOPOLOGY,
	ANN_HEADER_TRAINING_INFO,
	ANN_HEADER_TOTAL_NODE,
	ANN_THRESHOLD_VALUE,
	ANN_WEIGHT_FACTOR
};

extern char* ann_file_header[];

#endif
