#ifndef __ANN_FILE_HEADER_H__
#define __ANN_FILE_HEADER_H__

enum ANN_FILE_HEADER_LIST
{
	ANN_HEADER_APPLICATION,
	ANN_HEADER_TOPOLOGY,
	ANN_HEADER_TRAINING_INFO,
	ANN_HEADER_TOTAL_NODE,
	ANN_HEADER_THRESHOLD_VALUE,
	ANN_HEADER_WEIGHT_FACTOR
};

enum ANN_HEADER_APPLICATION_LIST
{
	ANN_HEADER_APPLICATION_MSG
};

enum ANN_HEADER_TOPOLOGY_LIST
{
	ANN_HEADER_TOPOLOGY_INPUTS,
	ANN_HEADER_TOPOLOGY_OUTPUTS,
	ANN_HEADER_TOPOLOGY_LAYERS,
	ANN_HEADER_TOPOLOGY_TRANSFER_FUNC
};

enum ANN_HEADER_TRAINING_INFO_LIST
{
	ANN_HEADER_TRAINING_INFO_LEARNING_RATE,
	ANN_HEADER_TRAINING_INFO_MOMENTUM_COEF,
};

enum ANN_HEADER_TOTAL_NODE_LIST
{
	ANN_HEADER_TOTAL_NODE_MSG
};

enum ANN_HEADER_THREDHOLD_VALUE_LIST
{
	ANN_HEADER_THRESHOLD_VALUE_MSG
};

enum ANN_HEADER_WEIGHT_LIST
{
	ANN_HEADER_WEIGHT_MSG
};

extern char* ann_file_header[];

#endif
